<?php

declare(strict_types=1);

/**
 * Seed data definitions for HappyHome (consumed by bin/seed.php).
 */

$img = static fn(string $id): string => "https://images.unsplash.com/photo-$id?w=1200&q=80";

$pool = [
    '1502672260266-1c1ef2d93688', '1522708323590-d24dbb6b0267', '1560448204-e02f11c3d0e2',
    '1493809842364-78817add7ffb', '1484154218962-a197022b5858', '1556912172-45b7abe8b7e1',
    '1554995207-c18c203602cb', '1567496898669-ee935f5f647a', '1571939228382-b2f2b585ce15',
    '1574362848149-11496d93a7c7', '1598928506311-c55ded91a20c', '1600210492486-724fe5c67fb0',
    '1600585154340-be6161a56a0c', '1600607687939-ce8a6c25118c', '1600566753086-00f18fb6b3ea',
    '1600573472592-401b489a3cdc',
];

$agents = [
    ['Sato Kenji', '03-6427-1101', 'k.sato@happyhome.jp'],
    ['Suzuki Aiko', '03-6427-1102', 'a.suzuki@happyhome.jp'],
    ['Takahashi Ren', '03-6427-1103', 'r.takahashi@happyhome.jp'],
    ['Watanabe Mei', '045-330-2201', 'm.watanabe@happyhome.jp'],
    ['Ito Daiki', '03-6427-1105', 'd.ito@happyhome.jp'],
    ['Yamamoto Sakura', '03-6427-1106', 's.yamamoto@happyhome.jp'],
];

$properties = [
    [
        'title' => 'Sunny 2LDK near Shibuya Station', 'title_ja' => '渋谷駅近くの陽当たり良好2LDK',
        'description' => 'Bright south-facing 2LDK just a 5-minute walk from Shibuya Station. Recently renovated with a modern system kitchen, floor heating in the living room and a wide balcony overlooking Dogenzaka.',
        'description_ja' => '渋谷駅徒歩5分、南向きで陽当たり良好な2LDK。システムキッチン・床暖房を備えたリノベーション済み物件。道玄坂を望むワイドバルコニー付き。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => true,
        'price' => 185000, 'management_fee' => 10000, 'deposit_months' => 1.0, 'key_money_months' => 1.0,
        'address' => '1-2-3 Dogenzaka, Shibuya-ku, Tokyo', 'address_ja' => '東京都渋谷区道玄坂1-2-3',
        'prefecture' => 'Tokyo', 'city' => 'Shibuya-ku', 'latitude' => 35.6580, 'longitude' => 139.7000,
        'nearest_station' => 'Shibuya Station (JR Yamanote Line)', 'nearest_station_ja' => '渋谷駅（JR山手線）',
        'station_walk_min' => 5, 'layout' => '2LDK', 'size_sqm' => 55.3, 'built_year' => 2018,
        'floor' => 7, 'total_floors' => 12, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'delivery_box', 'internet_free', 'system_kitchen', 'floor_heating'],
        'view_count' => 742,
    ],
    [
        'title' => 'Riverside 1LDK in Nakameguro', 'title_ja' => '中目黒・目黒川沿いの1LDK',
        'description' => 'Stylish 1LDK along the Meguro River, famous for its cherry blossoms. Walk-in closet, counter kitchen and a quiet residential setting two stops from Shibuya.',
        'description_ja' => '桜並木で有名な目黒川沿いのおしゃれな1LDK。ウォークインクローゼット、カウンターキッチン付き。渋谷から2駅の閑静な住宅街。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 168000, 'management_fee' => 8000, 'deposit_months' => 1.0, 'key_money_months' => 1.0,
        'address' => '2-7-12 Kamimeguro, Meguro-ku, Tokyo', 'address_ja' => '東京都目黒区上目黒2-7-12',
        'prefecture' => 'Tokyo', 'city' => 'Meguro-ku', 'latitude' => 35.6440, 'longitude' => 139.6989,
        'nearest_station' => 'Naka-Meguro Station (Tokyu Toyoko Line)', 'nearest_station_ja' => '中目黒駅（東急東横線）',
        'station_walk_min' => 6, 'layout' => '1LDK', 'size_sqm' => 42.0, 'built_year' => 2016,
        'floor' => 3, 'total_floors' => 8, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'walk_in_closet', 'counter_kitchen', 'delivery_box', 'city_gas'],
        'view_count' => 489,
    ],
    [
        'title' => 'Family House 3LDK in Kichijoji', 'title_ja' => '吉祥寺の3LDKファミリー一戸建て',
        'description' => 'Spacious detached house near Inokashira Park. Three bedrooms, a sunny garden, parking for one car and pets welcome — ideal for families seeking greenery with city access.',
        'description_ja' => '井の頭公園近くのゆとりある一戸建て。3LDK＋陽当たりの良い庭、駐車場1台分、ペット相談可。緑豊かな環境で子育てに最適。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 235000, 'management_fee' => null, 'deposit_months' => 2.0, 'key_money_months' => 1.0,
        'address' => '3-9-5 Kichijoji Minamicho, Musashino-shi, Tokyo', 'address_ja' => '東京都武蔵野市吉祥寺南町3-9-5',
        'prefecture' => 'Tokyo', 'city' => 'Musashino-shi', 'latitude' => 35.7003, 'longitude' => 139.5825,
        'nearest_station' => 'Kichijoji Station (JR Chuo Line)', 'nearest_station_ja' => '吉祥寺駅（JR中央線）',
        'station_walk_min' => 12, 'layout' => '3LDK', 'size_sqm' => 92.4, 'built_year' => 2009,
        'floor' => null, 'total_floors' => 2, 'category' => 'house',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['balcony', 'air_conditioner', 'bath_toilet_separate', 'system_kitchen', 'reheating_bath', 'gas_stove', 'city_gas'],
        'view_count' => 356,
    ],
    [
        'title' => 'Compact Studio steps from Ebisu', 'title_ja' => '恵比寿駅徒歩3分のコンパクトワンルーム',
        'description' => 'Brand-new 2024 studio three minutes from Ebisu Station. Auto-lock entrance, delivery box and free internet — perfect first apartment in one of Tokyo\'s most loved neighborhoods.',
        'description_ja' => '2024年築、恵比寿駅徒歩3分の新築ワンルーム。オートロック・宅配ボックス・インターネット無料。人気エリアでのはじめての一人暮らしに最適。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 98000, 'management_fee' => 7000, 'deposit_months' => 1.0, 'key_money_months' => 0.0,
        'address' => '1-8-14 Ebisunishi, Shibuya-ku, Tokyo', 'address_ja' => '東京都渋谷区恵比寿西1-8-14',
        'prefecture' => 'Tokyo', 'city' => 'Shibuya-ku', 'latitude' => 35.6467, 'longitude' => 139.7080,
        'nearest_station' => 'Ebisu Station (JR Yamanote Line)', 'nearest_station_ja' => '恵比寿駅（JR山手線）',
        'station_walk_min' => 3, 'layout' => '1R', 'size_sqm' => 22.1, 'built_year' => 2024,
        'floor' => 4, 'total_floors' => 10, 'category' => 'studio',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['autolock', 'air_conditioner', 'delivery_box', 'internet_free', 'washlet'],
        'view_count' => 611,
    ],
    [
        'title' => 'Elegant 2LDK for Sale in Jiyugaoka', 'title_ja' => '自由が丘・上質な2LDK分譲マンション',
        'description' => 'Refined 2LDK condominium in fashionable Jiyugaoka. Southwest corner unit with floor heating, walk-in closet and a calm tree-lined approach. A rare offering in this coveted district.',
        'description_ja' => 'おしゃれな街・自由が丘の上質な2LDK分譲マンション。南西角部屋、床暖房・ウォークインクローゼット付き。希少な邸宅エリアの物件です。',
        'transaction_type' => 'buy', 'status' => 'published', 'is_featured' => true,
        'price' => 68000000, 'management_fee' => 18500, 'deposit_months' => null, 'key_money_months' => null,
        'address' => '2-11-6 Jiyugaoka, Meguro-ku, Tokyo', 'address_ja' => '東京都目黒区自由が丘2-11-6',
        'prefecture' => 'Tokyo', 'city' => 'Meguro-ku', 'latitude' => 35.6076, 'longitude' => 139.6690,
        'nearest_station' => 'Jiyugaoka Station (Tokyu Toyoko Line)', 'nearest_station_ja' => '自由が丘駅（東急東横線）',
        'station_walk_min' => 7, 'layout' => '2LDK', 'size_sqm' => 63.4, 'built_year' => 2012,
        'floor' => 5, 'total_floors' => 9, 'category' => 'apartment',
        'pet_allowed' => true, 'parking_available' => false,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'floor_heating', 'walk_in_closet', 'system_kitchen', 'washlet'],
        'view_count' => 528,
    ],
    [
        'title' => 'Sky-high 3LDK Tower Residence in Shinjuku', 'title_ja' => '新宿の高層タワーレジデンス3LDK',
        'description' => '38th-floor residence in a 52-story tower with concierge, gym and guest rooms. Panoramic views of Mt. Fuji and the Tokyo skyline. Premium fixtures throughout.',
        'description_ja' => '52階建てタワーの38階に位置するレジデンス。コンシェルジュ・ジム・ゲストルーム完備。富士山と東京の夜景を一望できるプレミアム仕様。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => true,
        'price' => 450000, 'management_fee' => 25000, 'deposit_months' => 2.0, 'key_money_months' => 1.0,
        'address' => '6-15-1 Nishishinjuku, Shinjuku-ku, Tokyo', 'address_ja' => '東京都新宿区西新宿6-15-1',
        'prefecture' => 'Tokyo', 'city' => 'Shinjuku-ku', 'latitude' => 35.6938, 'longitude' => 139.6907,
        'nearest_station' => 'Shinjuku Station (JR Yamanote Line)', 'nearest_station_ja' => '新宿駅（JR山手線）',
        'station_walk_min' => 9, 'layout' => '3LDK', 'size_sqm' => 95.8, 'built_year' => 2020,
        'floor' => 38, 'total_floors' => 52, 'category' => 'tower',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['autolock', 'air_conditioner', 'bath_toilet_separate', 'delivery_box', 'floor_heating', 'concierge', 'gym', 'guest_room', 'elevator'],
        'view_count' => 894,
    ],
    [
        'title' => 'Designer 1LDK in Roppongi', 'title_ja' => '六本木のデザイナーズ1LDK',
        'description' => 'Contemporary 1LDK in a 2021 tower minutes from Roppongi Hills. Floor-to-ceiling windows, hotel-like lobby and 24-hour security for an international lifestyle.',
        'description_ja' => '六本木ヒルズ至近、2021年築タワー内のデザイナーズ1LDK。天井までの大開口窓、ホテルライクなロビー、24時間セキュリティ。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 320000, 'management_fee' => 15000, 'deposit_months' => 2.0, 'key_money_months' => 1.0,
        'address' => '4-2-8 Roppongi, Minato-ku, Tokyo', 'address_ja' => '東京都港区六本木4-2-8',
        'prefecture' => 'Tokyo', 'city' => 'Minato-ku', 'latitude' => 35.6628, 'longitude' => 139.7315,
        'nearest_station' => 'Roppongi Station (Hibiya Line)', 'nearest_station_ja' => '六本木駅（日比谷線）',
        'station_walk_min' => 4, 'layout' => '1LDK', 'size_sqm' => 54.2, 'built_year' => 2021,
        'floor' => 18, 'total_floors' => 27, 'category' => 'tower',
        'pet_allowed' => false, 'parking_available' => true,
        'amenities' => ['autolock', 'air_conditioner', 'delivery_box', 'internet_free', 'concierge', 'elevator', 'washlet', 'floor_heating'],
        'view_count' => 663,
    ],
    [
        'title' => 'Minatomirai Bayview 2LDK Tower for Sale', 'title_ja' => 'みなとみらい・ベイビュー2LDKタワー分譲',
        'description' => 'Corner 2LDK on the 24th floor overlooking Yokohama Bay and the Ferris wheel. Direct underground access to Minatomirai Station, sky lounge and fitness room.',
        'description_ja' => '横浜港と観覧車を望む24階角部屋2LDK。みなとみらい駅直結、スカイラウンジ・フィットネスルーム付きの分譲タワー。',
        'transaction_type' => 'buy', 'status' => 'published', 'is_featured' => true,
        'price' => 98500000, 'management_fee' => 22000, 'deposit_months' => null, 'key_money_months' => null,
        'address' => '3-5-1 Minatomirai, Nishi-ku, Yokohama, Kanagawa', 'address_ja' => '神奈川県横浜市西区みなとみらい3-5-1',
        'prefecture' => 'Kanagawa', 'city' => 'Yokohama Nishi-ku', 'latitude' => 35.4578, 'longitude' => 139.6325,
        'nearest_station' => 'Minatomirai Station (Minatomirai Line)', 'nearest_station_ja' => 'みなとみらい駅（みなとみらい線）',
        'station_walk_min' => 2, 'layout' => '2LDK', 'size_sqm' => 75.6, 'built_year' => 2019,
        'floor' => 24, 'total_floors' => 33, 'category' => 'tower',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'floor_heating', 'concierge', 'gym', 'elevator', 'delivery_box'],
        'view_count' => 577,
    ],
    [
        'title' => 'Cozy 1K in Koenji', 'title_ja' => '高円寺の落ち着く1K',
        'description' => 'Affordable 1K in lively Koenji, home of vintage shops and live houses. Quiet back street, refreshed interior, three minutes to the shopping arcade.',
        'description_ja' => '古着屋とライブハウスの街・高円寺のリーズナブルな1K。静かな裏通り、室内リフレッシュ済み、商店街まで徒歩3分。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 78000, 'management_fee' => 4000, 'deposit_months' => 1.0, 'key_money_months' => 0.0,
        'address' => '3-22-9 Koenjikita, Suginami-ku, Tokyo', 'address_ja' => '東京都杉並区高円寺北3-22-9',
        'prefecture' => 'Tokyo', 'city' => 'Suginami-ku', 'latitude' => 35.7052, 'longitude' => 139.6498,
        'nearest_station' => 'Koenji Station (JR Chuo-Sobu Line)', 'nearest_station_ja' => '高円寺駅（JR中央・総武線）',
        'station_walk_min' => 6, 'layout' => '1K', 'size_sqm' => 24.5, 'built_year' => 1998,
        'floor' => 2, 'total_floors' => 4, 'category' => 'studio',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['air_conditioner', 'city_gas', 'gas_stove'],
        'view_count' => 142,
    ],
    [
        'title' => 'Terrace 2LDK in Daikanyama', 'title_ja' => '代官山・テラス付き2LDK',
        'description' => 'Low-rise designer residence in Daikanyama with a private 20 sqm terrace. Pet-friendly, double-height living room and boutique shopping at the doorstep.',
        'description_ja' => '代官山の低層デザイナーズレジデンス。約20㎡のプライベートテラス付き、ペット可。吹き抜けリビングと充実の周辺環境。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => true,
        'price' => 298000, 'management_fee' => 12000, 'deposit_months' => 2.0, 'key_money_months' => 2.0,
        'address' => '14-6 Sarugakucho, Shibuya-ku, Tokyo', 'address_ja' => '東京都渋谷区猿楽町14-6',
        'prefecture' => 'Tokyo', 'city' => 'Shibuya-ku', 'latitude' => 35.6485, 'longitude' => 139.7031,
        'nearest_station' => 'Daikanyama Station (Tokyu Toyoko Line)', 'nearest_station_ja' => '代官山駅（東急東横線）',
        'station_walk_min' => 5, 'layout' => '2LDK', 'size_sqm' => 70.1, 'built_year' => 2017,
        'floor' => 2, 'total_floors' => 3, 'category' => 'apartment',
        'pet_allowed' => true, 'parking_available' => false,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'system_kitchen', 'floor_heating', 'walk_in_closet'],
        'view_count' => 731,
    ],
    [
        'title' => 'Retro-modern 1DK in Shimokitazawa', 'title_ja' => '下北沢のレトロモダン1DK',
        'description' => 'Charming 1DK in the theater-and-curry town of Shimokitazawa. Renovated wet areas, exposed-beam ceiling, and the reborn Shimokita green street below.',
        'description_ja' => '演劇とカレーの街・下北沢の趣ある1DK。水回りリノベ済み、現し梁の天井。再開発で生まれ変わった緑道沿い。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 112000, 'management_fee' => 6000, 'deposit_months' => 1.0, 'key_money_months' => 1.0,
        'address' => '2-12-3 Kitazawa, Setagaya-ku, Tokyo', 'address_ja' => '東京都世田谷区北沢2-12-3',
        'prefecture' => 'Tokyo', 'city' => 'Setagaya-ku', 'latitude' => 35.6614, 'longitude' => 139.6682,
        'nearest_station' => 'Shimokitazawa Station (Odakyu Line)', 'nearest_station_ja' => '下北沢駅（小田急線）',
        'station_walk_min' => 4, 'layout' => '1DK', 'size_sqm' => 30.2, 'built_year' => 2005,
        'floor' => 3, 'total_floors' => 5, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['air_conditioner', 'bath_toilet_separate', 'city_gas', 'washlet'],
        'view_count' => 264,
    ],
    [
        'title' => 'Prestige 4LDK House in Kagurazaka', 'title_ja' => '神楽坂の邸宅4LDK',
        'description' => 'Architect-designed residence on a quiet Kagurazaka lane. Four bedrooms, inner courtyard, two-car garage and seamless indoor-outdoor living across 132 sqm.',
        'description_ja' => '神楽坂の静かな路地に佇む建築家設計の邸宅。4LDK・中庭・ガレージ2台分。約132㎡の内外一体の住空間。',
        'transaction_type' => 'buy', 'status' => 'published', 'is_featured' => false,
        'price' => 210000000, 'management_fee' => null, 'deposit_months' => null, 'key_money_months' => null,
        'address' => '5-32-4 Kagurazaka, Shinjuku-ku, Tokyo', 'address_ja' => '東京都新宿区神楽坂5-32-4',
        'prefecture' => 'Tokyo', 'city' => 'Shinjuku-ku', 'latitude' => 35.7028, 'longitude' => 139.7401,
        'nearest_station' => 'Iidabashi Station (JR Chuo-Sobu Line)', 'nearest_station_ja' => '飯田橋駅（JR中央・総武線）',
        'station_walk_min' => 8, 'layout' => '4LDK+', 'size_sqm' => 132.5, 'built_year' => 2014,
        'floor' => null, 'total_floors' => 3, 'category' => 'house',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['air_conditioner', 'bath_toilet_separate', 'system_kitchen', 'floor_heating', 'walk_in_closet', 'reheating_bath', 'counter_kitchen'],
        'view_count' => 412,
    ],
    [
        'title' => 'Smart 1LDK for Sale near Meguro', 'title_ja' => '目黒駅近の堅実1LDK分譲',
        'description' => 'Sensible first purchase: a 45.9 sqm 1LDK six minutes from Meguro Station. Well-managed 2008 building, southeast light and low monthly costs.',
        'description_ja' => '目黒駅徒歩6分・45.9㎡の1LDK。管理良好な2008年築、南東向きで陽当たり良好。月々の負担を抑えたはじめての購入に。',
        'transaction_type' => 'buy', 'status' => 'published', 'is_featured' => false,
        'price' => 34800000, 'management_fee' => 12800, 'deposit_months' => null, 'key_money_months' => null,
        'address' => '2-15-19 Kamiosaki, Shinagawa-ku, Tokyo', 'address_ja' => '東京都品川区上大崎2-15-19',
        'prefecture' => 'Tokyo', 'city' => 'Shinagawa-ku', 'latitude' => 35.6339, 'longitude' => 139.7158,
        'nearest_station' => 'Meguro Station (JR Yamanote Line)', 'nearest_station_ja' => '目黒駅（JR山手線）',
        'station_walk_min' => 6, 'layout' => '1LDK', 'size_sqm' => 45.9, 'built_year' => 2008,
        'floor' => 6, 'total_floors' => 11, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'delivery_box', 'elevator'],
        'view_count' => 198,
    ],
    [
        'title' => 'Shitamachi 2DK near Asakusa', 'title_ja' => '浅草の下町情緒あふれる2DK',
        'description' => 'Generous 2DK in old-town Asakusa, five minutes from Senso-ji. Tatami room plus flooring DK, view of Tokyo Skytree from the balcony.',
        'description_ja' => '浅草寺まで徒歩5分、下町情緒あふれる2DK。和室＋フローリングDK。バルコニーから東京スカイツリーを望む。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 125000, 'management_fee' => 5000, 'deposit_months' => 1.0, 'key_money_months' => 1.0,
        'address' => '4-18-7 Asakusa, Taito-ku, Tokyo', 'address_ja' => '東京都台東区浅草4-18-7',
        'prefecture' => 'Tokyo', 'city' => 'Taito-ku', 'latitude' => 35.7118, 'longitude' => 139.7967,
        'nearest_station' => 'Asakusa Station (Ginza Line)', 'nearest_station_ja' => '浅草駅（銀座線）',
        'station_walk_min' => 9, 'layout' => '2DK', 'size_sqm' => 48.3, 'built_year' => 2001,
        'floor' => 5, 'total_floors' => 7, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['balcony', 'air_conditioner', 'bath_toilet_separate', 'city_gas', 'gas_stove'],
        'view_count' => 173,
    ],
    [
        'title' => 'Hillside 3LDK House in Yokohama Motomachi', 'title_ja' => '横浜元町・丘の上の3LDK一戸建て',
        'description' => 'Western-style hillside house above Motomachi shopping street. Harbor views, garden terrace, garage, and pets welcome. Yamate\'s historic charm at your door.',
        'description_ja' => '元町商店街を見下ろす丘の上の洋風一戸建て。港の眺望、ガーデンテラス、ガレージ付き、ペット可。山手の歴史ある街並みが魅力。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 210000, 'management_fee' => null, 'deposit_months' => 2.0, 'key_money_months' => 1.0,
        'address' => '2-88 Motomachi, Naka-ku, Yokohama, Kanagawa', 'address_ja' => '神奈川県横浜市中区元町2-88',
        'prefecture' => 'Kanagawa', 'city' => 'Yokohama Naka-ku', 'latitude' => 35.4437, 'longitude' => 139.6503,
        'nearest_station' => 'Motomachi-Chukagai Station (Minatomirai Line)', 'nearest_station_ja' => '元町・中華街駅（みなとみらい線）',
        'station_walk_min' => 7, 'layout' => '3LDK', 'size_sqm' => 105.0, 'built_year' => 2003,
        'floor' => null, 'total_floors' => 2, 'category' => 'house',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['balcony', 'air_conditioner', 'bath_toilet_separate', 'system_kitchen', 'reheating_bath', 'walk_in_closet'],
        'view_count' => 287,
    ],
    [
        'title' => 'Bright Office Floor near Shinagawa', 'title_ja' => '品川駅近・明るいオフィスフロア',
        'description' => 'Open-plan 88 sqm office two minutes from Shinagawa Station\'s Konan exit. OA flooring, individual AC, 24-hour access — ideal for a growing team of 10-20.',
        'description_ja' => '品川駅港南口徒歩2分、開放的な88㎡のオフィスフロア。OAフロア・個別空調・24時間入退館可。10〜20名規模の成長企業に最適。',
        'transaction_type' => 'rent', 'status' => 'published', 'is_featured' => false,
        'price' => 380000, 'management_fee' => 40000, 'deposit_months' => 6.0, 'key_money_months' => 0.0,
        'address' => '2-16-3 Konan, Minato-ku, Tokyo', 'address_ja' => '東京都港区港南2-16-3',
        'prefecture' => 'Tokyo', 'city' => 'Minato-ku', 'latitude' => 35.6285, 'longitude' => 139.7387,
        'nearest_station' => 'Shinagawa Station (JR Yamanote Line)', 'nearest_station_ja' => '品川駅（JR山手線）',
        'station_walk_min' => 2, 'layout' => null, 'size_sqm' => 88.0, 'built_year' => 2010,
        'floor' => 9, 'total_floors' => 15, 'category' => 'office',
        'pet_allowed' => false, 'parking_available' => true,
        'amenities' => ['autolock', 'air_conditioner', 'elevator', 'internet_free'],
        'view_count' => 96,
    ],
    [
        'title' => 'Quiet 2K near Omotesando', 'title_ja' => '表参道至近の静かな2K',
        'description' => 'Hidden-away 2K on a calm backstreet between Omotesando and Gaienmae. Retro 1999 building with updated kitchen; rare value for the address.',
        'description_ja' => '表参道と外苑前の間、静かな裏通りの2K。1999年築のレトロな建物にリニューアルキッチン。この立地では希少な掘り出し物。',
        'transaction_type' => 'rent', 'status' => 'draft', 'is_featured' => false,
        'price' => 158000, 'management_fee' => 8000, 'deposit_months' => 1.0, 'key_money_months' => 1.0,
        'address' => '3-4-11 Kita-Aoyama, Minato-ku, Tokyo', 'address_ja' => '東京都港区北青山3-4-11',
        'prefecture' => 'Tokyo', 'city' => 'Minato-ku', 'latitude' => 35.6652, 'longitude' => 139.7126,
        'nearest_station' => 'Omotesando Station (Ginza Line)', 'nearest_station_ja' => '表参道駅（銀座線）',
        'station_walk_min' => 5, 'layout' => '2K', 'size_sqm' => 38.6, 'built_year' => 1999,
        'floor' => 2, 'total_floors' => 6, 'category' => 'apartment',
        'pet_allowed' => false, 'parking_available' => false,
        'amenities' => ['air_conditioner', 'city_gas', 'gas_stove', 'system_kitchen'],
        'view_count' => 41,
    ],
    [
        'title' => 'Waterfront 3LDK Tower in Toyosu for Sale', 'title_ja' => '豊洲・ウォーターフロント3LDKタワー分譲',
        'description' => '2022-built bayside tower with a 3LDK corner plan, 82 sqm of smart-home living, kids\' room, sky deck and supermarket downstairs. Families love Toyosu\'s parks.',
        'description_ja' => '2022年築・湾岸タワーの角住戸3LDK。約82㎡のスマートホーム仕様、キッズルーム・スカイデッキ・スーパー直結。公園豊富な豊洲はファミリーに人気。',
        'transaction_type' => 'buy', 'status' => 'published', 'is_featured' => true,
        'price' => 115000000, 'management_fee' => 24500, 'deposit_months' => null, 'key_money_months' => null,
        'address' => '6-4-2 Toyosu, Koto-ku, Tokyo', 'address_ja' => '東京都江東区豊洲6-4-2',
        'prefecture' => 'Tokyo', 'city' => 'Koto-ku', 'latitude' => 35.6549, 'longitude' => 139.7967,
        'nearest_station' => 'Toyosu Station (Yurakucho Line)', 'nearest_station_ja' => '豊洲駅（有楽町線）',
        'station_walk_min' => 6, 'layout' => '3LDK', 'size_sqm' => 82.3, 'built_year' => 2022,
        'floor' => 29, 'total_floors' => 44, 'category' => 'tower',
        'pet_allowed' => true, 'parking_available' => true,
        'amenities' => ['autolock', 'balcony', 'air_conditioner', 'bath_toilet_separate', 'floor_heating', 'concierge', 'gym', 'guest_room', 'elevator', 'delivery_box'],
        'view_count' => 503,
    ],
];

// Attach 3-4 rotating Unsplash images to each property.
foreach ($properties as $i => &$p) {
    $count = 3 + ($i % 2); // alternate 3 / 4 images
    $images = [];
    for ($j = 0; $j < $count; $j++) {
        $images[] = $img($pool[($i * 3 + $j) % count($pool)]);
    }
    $p['images'] = $images;
    $p['floor_plan_url'] = ($i % 3 === 0)
        ? 'https://images.unsplash.com/photo-' . $pool[($i * 5 + 7) % count($pool)] . '?w=900&q=80'
        : null;
    $agent = $agents[$i % count($agents)];
    $p['agent_name'] = $agent[0];
    $p['agent_company'] = 'HappyHome Realty K.K.';
    $p['agent_phone'] = $agent[1];
    $p['agent_email'] = $agent[2];
}
unset($p);

return [
    'users' => [
        ['name' => 'HappyHome Admin', 'email' => 'admin@happyhome.jp', 'password' => 'HappyHome2026!', 'phone' => '03-6427-1100', 'role' => 'admin'],
        ['name' => 'Demo Tanaka', 'email' => 'demo@happyhome.jp', 'password' => 'Demo12345!', 'phone' => '090-1234-5678', 'role' => 'user'],
    ],
    'categories' => [
        ['name' => 'Apartment', 'name_ja' => 'マンション', 'slug' => 'apartment'],
        ['name' => 'House', 'name_ja' => '一戸建て', 'slug' => 'house'],
        ['name' => 'Studio', 'name_ja' => 'ワンルーム', 'slug' => 'studio'],
        ['name' => 'Tower Residence', 'name_ja' => 'タワーマンション', 'slug' => 'tower'],
        ['name' => 'Office', 'name_ja' => 'オフィス', 'slug' => 'office'],
    ],
    'properties' => $properties,
];
